/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'priceInINR' : IDL.Nat,
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const NewOrder = IDL.Record({
  'paymentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'totalAmountInINR' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
});
export const NotificationType = IDL.Variant({
  'paymentConfirmation' : IDL.Null,
  'orderPlaced' : IDL.Null,
  'orderStatusUpdated' : IDL.Null,
  'paymentFailure' : IDL.Null,
  'broadcast' : IDL.Null,
});
export const Time = IDL.Int;
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'orderStatus' : IDL.Opt(OrderStatus),
  'notificationType' : NotificationType,
  'user' : IDL.Opt(IDL.Principal),
  'isRead' : IDL.Bool,
  'orderId' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'created' : Time,
  'user' : IDL.Principal,
  'paymentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'totalAmountInINR' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'priceInINR' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const Document = IDL.Record({
  'content' : ExternalBlob,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'size' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBroadcastNotification' : IDL.Func([IDL.Text], [], []),
  'addDocument' : IDL.Func(
      [IDL.Vec(IDL.Nat8), ExternalBlob, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'addStarters' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearUserNotifications' : IDL.Func([IDL.Principal], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([NewOrder], [IDL.Nat], []),
  'deleteDocument' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'getAllNotificationsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBroadcastNotifications' : IDL.Func(
      [],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getNotificationById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Notification)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Opt(OrderStatus)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getPaginatedNotificationsByUser' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPendingOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getRestaurantLocation' : IDL.Func([], [IDL.Text], ['query']),
  'getRestaurantMapsUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getSingleDocument' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(Document)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnreadNotificationsCount' : IDL.Func(
      [IDL.Principal],
      [IDL.Nat],
      ['query'],
    ),
  'getUserActiveOrders' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUserNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getUserOrderHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'notificationsDebug' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'replaceCategoryMenuItems' : IDL.Func([IDL.Text, IDL.Vec(MenuItem)], [], []),
  'setMenuItemActiveStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setRestaurantLocation' : IDL.Func([IDL.Text], [], []),
  'setRestaurantMapsUrl' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'priceInINR' : IDL.Nat,
    'quantity' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const NewOrder = IDL.Record({
    'paymentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'totalAmountInINR' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const NotificationType = IDL.Variant({
    'paymentConfirmation' : IDL.Null,
    'orderPlaced' : IDL.Null,
    'orderStatusUpdated' : IDL.Null,
    'paymentFailure' : IDL.Null,
    'broadcast' : IDL.Null,
  });
  const Time = IDL.Int;
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'orderStatus' : IDL.Opt(OrderStatus),
    'notificationType' : NotificationType,
    'user' : IDL.Opt(IDL.Principal),
    'isRead' : IDL.Bool,
    'orderId' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'created' : Time,
    'user' : IDL.Principal,
    'paymentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'totalAmountInINR' : IDL.Nat,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'priceInINR' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Document = IDL.Record({
    'content' : ExternalBlob,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'size' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBroadcastNotification' : IDL.Func([IDL.Text], [], []),
    'addDocument' : IDL.Func(
        [IDL.Vec(IDL.Nat8), ExternalBlob, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'addStarters' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearUserNotifications' : IDL.Func([IDL.Principal], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([NewOrder], [IDL.Nat], []),
    'deleteDocument' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'getAllNotificationsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBroadcastNotifications' : IDL.Func(
        [],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getNotificationById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Notification)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderStatus' : IDL.Func([IDL.Nat], [IDL.Opt(OrderStatus)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getPaginatedNotificationsByUser' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPendingOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getRestaurantLocation' : IDL.Func([], [IDL.Text], ['query']),
    'getRestaurantMapsUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getSingleDocument' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(Document)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnreadNotificationsCount' : IDL.Func(
        [IDL.Principal],
        [IDL.Nat],
        ['query'],
      ),
    'getUserActiveOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getUserOrderHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'notificationsDebug' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'replaceCategoryMenuItems' : IDL.Func(
        [IDL.Text, IDL.Vec(MenuItem)],
        [],
        [],
      ),
    'setMenuItemActiveStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setRestaurantLocation' : IDL.Func([IDL.Text], [], []),
    'setRestaurantMapsUrl' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };