/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Document {
  'content' : ExternalBlob,
  'owner' : Principal,
  'name' : string,
  'size' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'priceInINR' : bigint,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'image' : [] | [ExternalBlob],
}
export interface NewOrder {
  'paymentId' : [] | [string],
  'items' : Array<OrderItem>,
  'totalAmountInINR' : bigint,
}
export interface Notification {
  'id' : bigint,
  'content' : string,
  'orderStatus' : [] | [OrderStatus],
  'notificationType' : NotificationType,
  'user' : [] | [Principal],
  'isRead' : boolean,
  'orderId' : [] | [bigint],
  'timestamp' : Time,
}
export type NotificationType = { 'paymentConfirmation' : null } |
  { 'orderPlaced' : null } |
  { 'orderStatusUpdated' : null } |
  { 'paymentFailure' : null } |
  { 'broadcast' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'created' : Time,
  'user' : Principal,
  'paymentId' : [] | [string],
  'items' : Array<OrderItem>,
  'totalAmountInINR' : bigint,
}
export interface OrderItem {
  'priceInINR' : bigint,
  'quantity' : bigint,
  'menuItemId' : bigint,
}
export type OrderStatus = { 'preparing' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBroadcastNotification' : ActorMethod<[string], undefined>,
  'addDocument' : ActorMethod<
    [Uint8Array, ExternalBlob, string, bigint],
    undefined
  >,
  'addMenuItem' : ActorMethod<
    [string, string, bigint, string, [] | [ExternalBlob]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearUserNotifications' : ActorMethod<[Principal], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[NewOrder], bigint>,
  'deleteDocument' : ActorMethod<[Uint8Array], undefined>,
  'getAllNotificationsByUser' : ActorMethod<[Principal], Array<Notification>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBroadcastNotifications' : ActorMethod<[], Array<Notification>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getNotificationById' : ActorMethod<[bigint], [] | [Notification]>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStatus' : ActorMethod<[bigint], [] | [OrderStatus]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getPaginatedNotificationsByUser' : ActorMethod<
    [Principal, bigint, bigint],
    Array<Notification>
  >,
  'getPendingOrders' : ActorMethod<[], Array<Order>>,
  'getRestaurantLocation' : ActorMethod<[], string>,
  'getRestaurantMapsUrl' : ActorMethod<[], string>,
  'getSingleDocument' : ActorMethod<[Uint8Array], [] | [Document]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnreadNotificationsCount' : ActorMethod<[Principal], bigint>,
  'getUserActiveOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserNotifications' : ActorMethod<[Principal], Array<Notification>>,
  'getUserOrderHistory' : ActorMethod<[Principal], Array<Order>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'notificationsDebug' : ActorMethod<[], Array<Notification>>,
  'replaceCategoryMenuItems' : ActorMethod<
    [string, Array<MenuItem>],
    undefined
  >,
  'setMenuItemActiveStatus' : ActorMethod<[bigint, boolean], undefined>,
  'setRestaurantLocation' : ActorMethod<[string], undefined>,
  'setRestaurantMapsUrl' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, bigint, string, [] | [ExternalBlob]],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];